name: dsplus_finance
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.0
  shared_preferences: ^2.2.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  equatable: ^2.0.5
  pin_code_fields: ^8.0.1
  pin_input_text_field: ^4.5.1
  flutter_svg_provider: ^1.0.6
  google_maps_flutter: ^2.5.0
  intl: ^0.19.0
  url_launcher: ^6.1.14
  permission_handler: ^11.0.1
  images_picker: ^1.2.11
  device_preview: ^1.1.0
  dio: ^5.3.3
  fluttertoast: ^8.2.2
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  injectable: ^2.3.5
  get_it: ^7.6.4
  dart_mappable: ^4.0.1
  currency_text_input_formatter: ^2.1.11
  image_field: ^0.0.8
  file_picker: ^6.1.1
  dotted_border: ^2.1.0
  firebase_storage: ^11.6.5
  image_picker: ^1.0.7
  easy_localization: ^3.0.4
  flutter_easyloading: ^3.0.5
  injectable_generator: ^2.4.2
  toggle_switch: ^2.3.0


dev_dependencies: 
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.6
  dart_mappable_builder: ^4.0.1
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/


  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Proxima Nova Alt
      fonts: 
        - asset: assets/fonts/ProximaNovaABold.ttf
          weight: 700
